module.exports = [{
    "id": 1,
    "name": "toy car",
    "owner_user_id": 1,
    "age": "12M",
    "gender": null,
    "image_path":"./car.jpg",
    "category": "toys",
    "available": true,
    "city": "Tel Aviv",
    "Price": 20,
    },
    {   
        "id": 2,
        "name": "red dress",
        "owner_user_id": 1,
        "age": "8M",
        "gender": "girl",
        "image_path":"./dress.jpeg",
        "category": "clothes",
        "available": true,
        "city": "Haifa",
        "Price": 10,
    },
    {
        "id": 3,
        "name": "xylophone",
        "owner_user_id": 2,
        "age": "18M",
        "gender": null,
        "image_path":"./Xylophone.jpg",
        "category": "toys",
        "available": true,
        "city": "Jerusalem",
        "Price": 20,
    },
    {
        "id": 4,
        "name": "pink overall",
        "owner_user_id": 2,
        "age": "12M",
        "gender": "girl",
        "image_path":"./pinkonsie.jpg",
        "category": "clothes",
        "available": true,
        "city": "Jerusalem",
        "Price": 20,
    }
    ,
    {
        "id": 5,
        "name": "loud toy",
        "owner_user_id": 2,
        "age": "6M",
        "gender": null,
        "image_path":"./noise.png",
        "category": "toys",
        "available": true,
        "city": "Jerusalem",
        "Price": 20,
    },
    {
        "id": 6,
        "name": "The Elephant who wanted to be the best",
        "owner_user_id": 1,
        "age": "24M",
        "gender": null,
        "image_path":"./elephant.jpg",
        "category": "books",
        "available": true,
        "city": "Tel Aviv",
        "Price": 25,
    },
    {
        "id": 7,
        "name": "Cactus",
        "owner_user_id": 1,
        "age": "18M",
        "gender": null,
        "image_path":"./cactus.png",
        "category": "toys",
        "available": true,
        "city": "Tel Aviv",
        "Price": 20,
    }
    ];
