module.exports = [{
    "id": 1,
    "name": "toy car",
    "owner_user_id": 1,
    "age": "12M",
    "gender": null,
    "image_path":"./car.jpg",
    "category": "toys",
    "available": true,
    "city": "Tel Aviv",
    "Price": 20,
    },
    {   
        "id": 2,
        "name": "red dress",
        "owner_user_id": 1,
        "age": "8M",
        "gender": "girl",
        "image_path":"./dress.jpeg",
        "category": "cloths",
        "available": true,
        "city": "Haifa",
        "Price": 10,
    }];
